---
title: "Data 607 project 2__3"
author: "Miguel Gomez"
date: "2023-02-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
  library(data.table)
  library(tidyr) 
  library(tidyverse)
 library(dplyr)
```

<font size="5">
The third data set I decided to use was : https://bbhosted.cuny.edu/webapps/discussionboard/do/message?action=list_messages&course_id=_2230790_1&nav=discussion_board_entry&conf_id=_2679745_1&forum_id=_3575059_1&message_id=_65572943_1

```{r}
data1 <- read.csv("C:\\Users\\hotga\\Desktop\\Copy of example __3 - Sheet1.CSV", header=TRUE, stringsAsFactors=FALSE)

data1
```

<font size="5"> Using melt function from data.table to convert wide data to long.
```{r}
melt_data <- melt(as.data.table(data1))
melt_data2 <- melt_data[!(melt_data$variable =='X'),]
colnames(melt_data2) <- c("Country", "Year", "populations")
melt_data2
```
<font size="5">
Removing "X" from Year column.
```{r}
melt_data2$Year <-gsub("X","",as.character(melt_data2$Year))
melt_data2
```
<font size="5">
Calculating Growth rate per country

```{r}
melt_data2 <- melt_data2 %>% group_by(Country) %>% mutate(Growth = (populations - lag(populations))/lag(populations))  
melt_data2

```
<font size="5">
Graphing the Growth rate per country. Mexico has the highest growth rate while USA has the lowest.

```{r}
ggplot(data = melt_data2, aes(x = Year, y = Growth, group=1)) + geom_line() +geom_point()+
   stat_smooth(method = "lm", se = FALSE) + facet_wrap(~Country)
```  
<font size="5">

Graphing the population by year. USA leads all three years while Canada is in last place. 

```{r}
options(scipen = 999)
data2 <- ggplot(melt_data2, aes(x=Year, y=populations, fill=Country))
data2 <- data2 + ggtitle('Population by Year') + theme(plot.title = element_text(hjust = 0.5))
data2 <- data2 + geom_text(aes(label=Country), vjust=1000,
position = position_dodge(1), size=3.5) +
scale_fill_brewer(palette="Paired") +
geom_bar(stat="identity", position=position_dodge())
data2
```









