---
title: "Data 607 Project 2_1"
author: "Miguel Gomez"
date: "2023-02-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
  library(data.table)
  library(tidyr) 
  library(tidyverse)
```

<font size="5"> The first data set I decided to use was: <https://bbhosted.cuny.edu/webapps/discussionboard/do/message?action=list_messages&course_id=_2230790_1&nav=discussion_board_entry&conf_id=_2679745_1&forum_id=_3575059_1&message_id=_65490755_1>

```{r}
data1 <- read.csv("C:\\Users\\hotga\\Desktop\\untidyexample1 - Sheet1.csv", header=TRUE, stringsAsFactors=FALSE)

data1
```

<font size="5"> Using melt function from data.table to convert wide data to long.

```{r}
melt_data <- melt(as.data.table(data1))
melt_data2 <- melt_data[!(melt_data$variable =='X'),]
colnames(melt_data2) <- c("Candidate", "State", "Votes")
melt_data2
```

<font size="5"> Total votes for each candidate: Jill Stein received the least amount of votes at 230,330 in California and Florida combined while Hillary Clinton received the most at 10,417,028. Donald Trump came in second at 7,790,236.

```{r}
total <- aggregate(melt_data2$Votes, list(melt_data2$Candidate), FUN=sum)
total
```


<font size="5"> Votes by State: 

```{r}
options(scipen = 999)
data2 <- ggplot(melt_data2, aes(x=Candidate, y=Votes, fill=State))
data2 <- data2 + ggtitle('Votes by State') + theme(plot.title = element_text(hjust = 0.5))
data2 <- data2 + geom_text(aes(label=State), vjust=1000,
position = position_dodge(1), size=3.5) +
scale_fill_brewer(palette="Paired") +
geom_bar(stat="identity", position=position_dodge())
data2
```
